stages:
  - deploy

deploy_dbg:
  tags:
    - fxh87common
  stage: deploy
  only:
    - develop
  script:
    - 'cd FXH.CMS.Web/'
    - 'dotnet restore -s https://repo.fxh.io:8443/repository/nuget-group/ -r centos.7-x64'
    - 'supervisorctl stop testadmin'
    - 'dotnet publish -c Release -r centos.7-x64 -o ~/build/testadmin'
    - 'supervisorctl start testadmin'

deploy_release:
  tags:
    - fxh87common
  stage: deploy
  only:
    - master
  script:
    - 'cd FXH.CMS.Web/'
    - 'dotnet restore -s https://repo.fxh.io:8443/repository/nuget-group/ -r centos.7-x64'
    - 'supervisorctl stop admin'
    - 'dotnet publish -c Release -r centos.7-x64 -o ~/build/admin'
    - 'supervisorctl start admin'
    - 'rm -f ~/build/admin/appsettings.Development.json'